/**
 * OBS bridge contract — the obs-websocket v5 client.
 *
 * The bridge is an OUTBOUND client to the local OBS WebSocket server
 * (default 127.0.0.1:4455): it never listens on a port of its own — the
 * gateway stays the only listening surface. It speaks the v5 handshake
 * (Hello → Identify → Identified, with challenge/salt SHA-256 password
 * auth), forwards OBS events onto the internal bus as `obs:<eventType>`,
 * and keeps OBS browser-source URLs in sync with the gateway (URL is
 * generated by the gateway, token auto-embedded, re-written on
 * `gateway:port-changed`).
 */

export type ObsConnectionStatus = 'disconnected' | 'connecting' | 'connected'

/** A persisted browser-source binding: an OBS input fed by a gateway route. */
export interface ObsBrowserSourceBinding {
  /** OBS input (source) name. */
  sourceName: string
  /** Gateway route path; the URL comes from `getBrowserSourceUrl(path)`. */
  path: string
}

/** Runtime state of one binding (diagnostics). */
export interface ObsBrowserSourceStatus extends ObsBrowserSourceBinding {
  synced: boolean
  lastError?: string
}

/** Bridge state snapshot (diagnostics page / T12). */
export interface ObsDiagnostics {
  status: ObsConnectionStatus
  port: number
  /** Failed connection attempts since the last successful connection. */
  attempts: number
  lastError?: string
  lastConnectedAt?: number
  requestsSent: number
  responsesReceived: number
  browserSources: ObsBrowserSourceStatus[]
}

/** obs-websocket request status block. */
export interface ObsRequestStatus {
  result: boolean
  code: number
  comment?: string
}

/**
 * Result of one request. Transport-level failures (not connected,
 * connection closed, timeout) REJECT from `send`; OBS-level failures
 * resolve with `ok: false` and the raw status.
 */
export interface ObsRequestResult<T = unknown> {
  ok: boolean
  status: ObsRequestStatus
  data?: T
}

/**
 * The OBS bridge.
 *
 * - `connect()`     starts the connection (and the auto-reconnect loop
 *   with exponential backoff). It never throws and never blocks startup:
 *   OBS-not-running resolves with status `disconnected` and diagnostics.
 * - `disconnect()`  stops the client and the retry loop; `reconnect()`
 *   resets the backoff and connects immediately.
 * - `send()`        issues any obs-websocket v5 request (scenes, sources,
 *   filters, volumes, transitions, record, stream — read AND write).
 * - OBS events are republished on the internal bus as `obs:<eventType>`
 *   (source `obs`) so any module can subscribe.
 * - `bindBrowserSource()` registers a persisted binding; bindings are
 *   synced on connect and on `gateway:port-changed`: existing sources get
 *   their URL updated (only on change), missing sources are created in the
 *   current program scene. The URL embeds the gateway token and is never
 *   logged.
 */
export interface IObsBridge {
  connect(): Promise<void>
  disconnect(): void
  reconnect(): Promise<void>
  send<T = unknown>(requestType: string, requestData?: unknown): Promise<ObsRequestResult<T>>
  bindBrowserSource(sourceName: string, path: string): void
  unbindBrowserSource(sourceName: string): void
  listBrowserSources(): ObsBrowserSourceBinding[]
  diagnostics(): ObsDiagnostics
}
